# Generated by Django 5.1.6 on 2025-07-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
