# Generated by Django 5.1.6 on 2025-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_profile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_type',
            field=models.CharField(choices=[('button', 'Button'), ('card', 'Card'), ('navbar', 'Navbar'), ('header', 'Header'), ('form', 'Form'), ('input', 'Input'), ('loader', 'Loader'), ('radio', 'Radio Button'), ('other', 'Other')], max_length=20),
        ),
    ]
