# Generated by Django 5.1.6 on 2025-07-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_design_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='likes',
        ),
    ]
